version: "3.8"
services:
  spocon-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      MYSQL_DATABASE: spocon
      MYSQL_HOST: spocon-mysql-ex
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql
    volumes:
      - .:/app
  mysql:
    image: mysql:8.0
    container_name: spocon-mysql-ex
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - 3306:3306
    volumes:
      - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d