version: "3"

vars:
  JOIN_COMMAND: join .Imports " "

tasks:
  setup:
    cmds:
      - go env -w GOBIN=$(pwd)/bin
      - go install $(go list -e -f {{ "'{{ " }} {{.JOIN_COMMAND}} {{ "}}' " }} tools/tools.go)
  up:
    cmds:
      - docker-compose up -d --build
      - docker exec -it spocon-backend_spocon-backend_1 go run tools/migrate.go