version: "3"

vars:
  ADD_PATH: env PATH="$(pwd)/bin:$PATH"
  JOIN_COMMAND: join .Imports " "

tasks:
  setup:
    desc: "開発に必要なGo製ツールをインストールします。"
    cmds: 
      - GOBIN=$(pwd)/bin go install $(go list -e -f {{ "'{{ " }} {{.JOIN_COMMAND}} {{ "}}' " }} tools/tools.go)
  up:
    desc: "spocon-backendで利用するコンテナ郡を立ち上げます。"
    cmds:
      - docker-compose up -d --build
      - docker exec -it spocon-backend_spocon-backend_1 go run -tags=migrate ./internal/tools/migrations/main.go up
  migration-up:
    desc: "全てのマイグレーションを実行します。"
    cmds:
      - docker exec -it spocon-backend_spocon-backend_1 go run -tags=migrate ./internal/tools/migrations/main.go up
  migration-down:
    desc: "全てのマイグレーションを戻して、テーブル削除まで行います。"
    cmds:
      - docker exec -it spocon-backend_spocon-backend_1 go run -tags=migrate ./internal/tools/migrations/main.go down
  migration-force:
    desc: "引数に指定したマイグレーションファイルのバージョンに強制的に戻し、マイグレーションの再実行が可能な状態にします。"
    cmds:
      - docker exec -it spocon-backend_spocon-backend_1 go run -tags=migrate ./internal/tools/migrations/main.go force {{.CLI_ARGS}}
  migration-step:
    desc: "引数に指定したマイグレーションファイルのバージョンまでマイグレーションを実行します。マイグレーションを適用したい場合は正の数、戻したい場合は負の数を指定する。"
    cmds:
      - docker exec -it spocon-backend_spocon-backend_1 go run -tags=migrate ./internal/tools/migrations/main.go step {{.CLI_ARGS}}
  oapi:
    desc: "OpenAPIの定義からGoのコードを生成します。"
    cmds:
      - "{{.ADD_PATH}} oapi-codegen -generate echo-server -o ./internal/openapi/server.gen.go ./openapi/openapi.yaml"
      - "{{.ADD_PATH}} oapi-codegen -generate types -o ./internal/openapi/types.gen.go ./openapi/openapi.yaml"