openapi: 3.0.3
info:
  version: 1.0.0
  title: spocon-backend
  discription: spocon-backend Open API 
servers:
  - url: /
paths:
  /health:
    get:
      summary: ヘルスチェック
      operationId: health-check
      tags:
        - health
      responses:
        '200':
          description: ヘルスチェックが成功した場合
          content: {}
  /grades:
    get:
      summary: グレード情報一覧の取得する
      operationId: get-grades
      tags:
        - grades
      responses:
        '200':
          description: グレード情報一覧の取得が成功した場合
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/GetGradesResponse'
  /teams:
    post: 
      summary: チームの登録
      operationId: create-team
      tags:
        - team
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTeamRequest'
              type: object
              required:
                - name
                - sport_id
                - grade_id
                - icon_path
                - description
                - address_state
                - address_city
              properties:
                name:
                  type: string
                sport_id:
                  type: string
                grade_id:
                  type: string
                icon_path:
                  type: string
                description:
                  type: string
                address_state:
                  type: string
                address_city:
                  type: string
      responses:
        '201':
          description: チームの作成が成功した場合
          content: {}
        '400':
          description: リクエスト形式が正しくない場合
          content: {}
components:
  schemas:
    GetGradesResponse:
      type: object
      required:
        - grades
      properties:
        grades:
          type: array
          items:
            $ref: '#/components/schemas/Grade'
    Grade:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
        name:
          type: string
    CreateTeamRequest:
      type: object
      required:
        - name
        - sport_id
        - grade_id
        - icon_path
        - description
        - address_state
        - address_city
      properties:
        name:
          type: string
        sport_id:
          type: string
        grade_id:
          type: string
        icon_path:
          type: string
        description:
          type: string
        address_state:
          type: string
        address_city:
          type: string
