openapi: 3.0.3
info:
  version: 1.0.0
  title: rest-api-sample
  discription: A sample Open API 
servers:
  - url: /
paths:
  /health:
    get:
      summary: ヘルスチェック
      operationId: health-check
      tags:
        - health
      responses:
        '200':
          description: ヘルスチェックが成功した場合
          content: {}
        '400':
          description: リクエスト形式が正しくない場合
          content: {}
  /user:
    post:
      summary: ユーザーの作成
      operationId: create-user
      tags:
        - user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        '201':
          description: ユーザーの作成が成功した場合
          content: {}
        '400':
          description: リクエスト形式が正しくない場合
          content: {}
components:
  schemas:
    User:
      type: object
      required:
        - name
        - email
      properties:
        name:
          type: string
        email:
          type: string