openapi: 3.0.3
info:
  version: 1.0.0
  title: spocon-backend
  discription: spocon-backend Open API 
servers:
  - url: /
paths:
  /health:
    get:
      summary: ヘルスチェック
      operationId: health-check
      tags:
        - health
      responses:
        '200':
          description: ヘルスチェックが成功した場合
          content: {}
  /grades:
    get:
      summary: グレード情報一覧の取得する
      operationId: get-grades
      tags:
        - grades
      responses:
        '200':
          description: グレード情報一覧の取得が成功した場合
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/GetGradesResponse'
  /user:
    get:
      summary: ユーザーの取得
      operationId: get-user
      tags:
        - user
      parameters:
        - name: id
          in: query
          description: ユーザーID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ユーザーの取得が成功した場合
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserResponse'
        '400':
          description: リクエスト形式が正しくない場合
          content: {}
    post:
      summary: ユーザーの作成
      operationId: create-user
      tags:
        - user
      responses:
        '201':
          description: ユーザーの作成が成功した場合
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/CreateUserResponse'
        '400':
          description: リクエスト形式が正しくない場合
          content: {}
components:
  schemas:
    GetGradesResponse:
      type: object
      required:
        - grades
      properties:
        grades:
          type: array
          items:
            type: object
            required:
              - id
              - name
            properties:
              id:
                type: string
              name:
                type: string
    GetUserResponse:
      type: object
      required:
        - id
        - name
        - email
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
    CreateUserResponse:
      type: object
      required:
        - name
        - email
      properties:
        name:
          type: string
        email:
          type: string