// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package openapi

// CreateUserResponse defines model for CreateUserResponse.
type CreateUserResponse struct {
	Email string `json:"email"`
	Name  string `json:"name"`
}

// GetGradesResponse defines model for GetGradesResponse.
type GetGradesResponse struct {
	Grades []struct {
		Id   string `json:"id"`
		Name string `json:"name"`
	} `json:"grades"`
}

// GetUserResponse defines model for GetUserResponse.
type GetUserResponse struct {
	Email string `json:"email"`
	Id    string `json:"id"`
	Name  string `json:"name"`
}

// GetUserParams defines parameters for GetUser.
type GetUserParams struct {
	// Id ユーザーID
	Id string `form:"id" json:"id"`
}
