name: check
on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Set up golines
        run: go install github.com/segmentio/golines # バージョンを指定しなければgo.modに記載されたバージョンがインストールされる
      - name: Check by golines
        run: |
        [ golines --dry-run -m 120 --base-formatter=gofmt . | wc -l) -eq 0 ] && exit "Pass" || (echo "Please Run 'task golines'" && exit 1)
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: 1.59.1
          args: --timeout 5m
      - name: Run tests
        run: go test -race ./...

